// Telc B2 Listening Comprehension (Hörverstehen) Database
window.listeningQuestionsSets = [
  // ==================== TEST SET 1 ====================
  {
    setId: 1,
    parts: [
      {
        part: "Teil 1",
        title: "Hörverstehen (Globalverstehen)",
        description: "Sie hören fünf kurze Aussagen von verschiedenen Personen zu einem Thema. Entscheiden Sie bei den Aufgaben 41-45, ob die jeweilige Aussage Richtig oder Falsch ist. Sie hören die Aussagen nur einmal.",
        topic: "Thema: Nutzung von Smartphones an Schulen",
        items: [
          { id: 41, speaker: "Sprecher 1", audioScript: "Meiner Meinung nach haben Smartphones im Unterricht absolut nichts verloren. Sie lenken die Schüler nur ab. Ständig summt oder vibriert ein Gerät, und die Jugendlichen konzentrieren sich überhaupt nicht mehr auf das, was der Lehrer an der Tafel erklärt. Schulen sollten handyfreie Zonen sein.", statement: "Sprecher 1 fordert ein komplettes Verbot von Smartphones an Schulen.", correctAnswer: "Richtig" },
          { id: 42, speaker: "Sprecher 2", audioScript: "Man kann die Technologie doch nicht einfach ignorieren! Smartphones sind Teil unserer Lebensrealität. Wir sollten Schülern lieber beibringen, wie man diese Geräte sinnvoll für Recherchen und zum Lernen nutzt, anstatt sie einfach nur zu verbieten.", statement: "Sprecher 2 ist der Ansicht, dass Smartphones im Unterricht als Lernwerkzeug dienen sollten.", correctAnswer: "Richtig" },
          { id: 43, speaker: "Sprecher 3", audioScript: "Klar, in den Pausen ist es okay, wenn die Kids auf ihr Handy schauen, um Musik zu hören oder ihren Eltern eine Nachricht zu schreiben. Aber im Klassenzimmer während des Unterrichts? Nein, das geht gar nicht. Da muss das Handy in der Tasche bleiben und stummgeschaltet sein.", statement: "Sprecher 3 möchte, dass Handys auch in den Schulpausen verboten werden.", correctAnswer: "Falsch" },
          { id: 44, speaker: "Sprecher 4", audioScript: "Bei uns an der Schule gibt es strenge Regeln, aber niemand hält sich daran. Die Lehrer haben gar keine Zeit, ständig zu kontrollieren, ob jemand unter dem Tisch chattet. Ein Verbot nützt also überhaupt nichts, weil es in der Praxis gar nicht kontrolliert werden kann.", statement: "Sprecher 4 findet Verbote sinnvoll, weil sie leicht durchzusetzen sind.", correctAnswer: "Falsch" },
          { id: 45, speaker: "Sprecher 5", audioScript: "Meine Kinder nutzen an ihrer Schule spezielle Lern-Apps auf dem Tablet. Das finde ich super. Aber das private Smartphone lenkt einfach zu sehr ab, besonders wegen der sozialen Medien. Deshalb bin ich dafür, private Geräte im Schulgebäude komplett zu verbieten.", statement: "Sprecher 5 befürwortet die Nutzung von Schul-Tablets, ist aber gegen private Smartphones im Unterricht.", correctAnswer: "Richtig" }
        ]
      },
      {
        part: "Teil 2",
        title: "Hörverstehen (Detailverstehen)",
        description: "Sie hören ein Gespräch oder Interview. Wählen Sie bei den Aufgaben 46-55 die richtige Antwort (a, b oder c). Sie hören den Text nur einmal.",
        topic: "Interview: Nachhaltiges Reisen und Ökotourismus",
        audioScript: "Moderator: Herzlich willkommen zu unserer Sendung 'Grüner Leben'. Heute im Studio zu Gast ist Dr. Claudia Weber, Expertin für Tourismusforschung. Frau Dr. Weber, das Thema nachhaltiges Reisen wird immer beliebter. Aber was genau versteht man eigentlich unter Ökotourismus?\n\nDr. Weber: Guten Tag. Ökotourismus bedeutet im Wesentlichen, so zu reisen, dass die Natur geschont und die lokale Bevölkerung vor Ort wirtschaftlich unterstützt wird. Es geht nicht darum, gar nicht mehr zu verreisen, sondern bewusster zu wählen. Zum Beispiel sollte man Flüge vermeiden, wo es geht, und stattdessen die Bahn nutzen.\n\nModerator: Viele Menschen argumentieren aber, dass Bahnreisen viel teurer und unzuverlässiger sind als Flüge. Ist Umweltschutz also ein Luxus?\n\nDr. Weber: Das stimmt leider teilweise, wenn man nur auf den Ticketpreis schaut. Aber wir müssen langfristig denken. Außerdem kann man auch am Urlaubsort viel sparen, indem man in lokalen Pensionen statt in riesigen Hotelketten übernachtet und regionale Produkte kauft. Das schont den Geldbeutel und hilft den Menschen vor Ort direkt.\n\nModerator: Ein großes Problem ist ja auch der sogenannte Massentourismus an beliebten Orten wie Venedig oder Mallorca. Haben Sie da einen Tipp?\n\nDr. Weber: Ja, absolut. Man sollte antizyklisch reisen, also außerhalb der Hauptsaison. Oder man wählt Reiseziele, die noch nicht vom Massentourismus überlaufen sind. Deutschland und die Nachbarländer bieten wunderschöne Ecken, die kaum jemand auf dem Schirm hat. Man muss nicht immer elf Stunden im Flugzeug sitzen, um ein Abenteuer zu erleben.\n\nModerator: Frau Dr. Weber, vielen Dank für diese interessanten Einblicke.",
        questions: [
          { id: 46, question: "Wer ist heute zu Gast in der Sendung?", options: [{ id: "a", text: "Eine Forscherin für Tourismus." }, { id: "b", text: "Die Inhaberin eines Reisebüros." }, { id: "c", text: "Eine Urlauberin, die von ihren Reisen berichtet." }], correctAnswer: "a" },
          { id: 47, question: "Was ist ein Hauptziel des Ökotourismus laut Dr. Weber?", options: [{ id: "a", text: "Urlaub komplett zu Hause zu verbringen." }, { id: "b", text: "Die lokale Bevölkerung finanziell zu stärken und die Natur zu schonen." }, { id: "c", text: "Möglichst billige Unterkünfte weltweit zu finden." }], correctAnswer: "b" },
          { id: 48, question: "Was empfiehlt die Expertin bezüglich des Transportmittels?", options: [{ id: "a", text: "Man sollte für alle Reisen das Flugzeug nehmen." }, { id: "b", text: "Man sollte Langstreckenflüge durch Inlandsflüge ersetzen." }, { id: "c", text: "Man sollte wenn möglich mit dem Zug reisen." }], correctAnswer: "c" },
          { id: 49, question: "Welchen Einwand bringt der Moderator bezüglich Bahnreisen?", options: [{ id: "a", text: "Sie seien oft teurer und unzuverlässiger als Flüge." }, { id: "b", text: "Sie seien extrem umweltschädlich." }, { id: "c", text: "Es gebe nicht genug Zugverbindungen ins Ausland." }], correctAnswer: "a" },
          { id: 50, question: "Wie kann man laut Dr. Weber am Urlaubsort Geld sparen?", options: [{ id: "a", text: "Indem man gar nichts einkauft." }, { id: "b", text: "Indem man in großen internationalen Hotelketten wohnt." }, { id: "c", text: "Indem man lokale Pensionen bucht und regionale Lebensmittel kauft." }], correctAnswer: "c" },
          { id: 51, question: "Was ist ein Problem bei bekannten Reisezielen?", options: [{ id: "a", text: "Der extreme Massentourismus." }, { id: "b", text: "Der Mangel an Sehenswürdigkeiten." }, { id: "c", text: "Dass dort keine Flugzeuge landen dürfen." }], correctAnswer: "a" },
          { id: 52, question: "Was bedeutet 'antizyklisch reisen'?", options: [{ id: "a", text: "Nur bei gutem Wetter zu reisen." }, { id: "b", text: "Außerhalb der touristischen Hauptsaison zu verreisen." }, { id: "c", text: "Ausschließlich mit dem Fahrrad zu fahren." }], correctAnswer: "b" },
          { id: 53, question: "Welche alternativen Reiseziele schlägt Dr. Weber vor?", options: [{ id: "a", text: "Exotische Inseln in Asien." }, { id: "b", text: "Bekannte Großstädte in den USA." }, { id: "c", text: "Regionen in Deutschland und den Nachbarländern." }], correctAnswer: "c" },
          { id: 54, question: "Wie steht Dr. Weber zu Fernreisen?", options: [{ id: "a", text: "Sie hält sie für absolut unverzichtbar." }, { id: "b", text: "Man muss für ein Abenteuer nicht unbedingt eine lange Flugreise machen." }, { id: "c", text: "Sie möchte Fernreisen gesetzlich verbieten lassen." }], correctAnswer: "b" },
          { id: 55, question: "Welcher Grundgedanke prägt das gesamte Interview?", options: [{ id: "a", text: "Reisen sollte bewusster und rücksichtsvoller gestaltet werden." }, { id: "b", text: "Tourismus zerstört jede Wirtschaft." }, { id: "c", text: "Autofahren ist besser als Zugfahren." }], correctAnswer: "a" }
        ]
      },
      {
        part: "Teil 3",
        title: "Hörverstehen (Selektives Verstehen)",
        description: "Sie hören fünf kurze Ansagen (z.B. im Radio oder an Bahnhöfen). Entscheiden Sie bei den Aufgaben 56-60, ob die Aussage Richtig oder Falsch ist. Sie hören die Ansagen nur einmal.",
        items: [
          { id: 56, speaker: "Ansage 1", audioScript: "Achtung am Gleis 4. Der Intercity-Express ICE 592 nach Hamburg Altona über Hannover, planmäßige Abfahrt um 14:15 Uhr, fährt heute wegen einer Signalstörung von Gleis 7 ab. Wir bitten die Fahrgäste, die Unterführung zu nutzen und auf Gleis 7 zu wechseln. Der Zug hat zusätzlich eine Verspätung von ca. zehn Minuten.", statement: "Der Zug nach Hamburg fährt heute von einem anderen Gleis ab als normalerweise.", correctAnswer: "Richtig" },
          { id: 57, speaker: "Ansage 2", audioScript: "Hier ist der Staumelder für die A8 Stuttgart Richtung München. Zwischen Gruibingen und Mühlhausen gibt es derzeit fünf Kilometer stockenden Verkehr wegen einer Baustelle. Autofahrern wird empfohlen, das Gebiet weiträumig über die Bundesstraße B10 zu umfahren.", statement: "Auf der A8 fließt der Verkehr wegen eines Unfalls nur sehr langsam.", correctAnswer: "Falsch" },
          { id: 58, speaker: "Ansage 3", audioScript: "Sehr geehrte Fluggäste des Fluges LH 2034 nach London Heathrow. Aufgrund von dichtem Nebel über London verzögert sich der Abflug um voraussichtlich zwei Stunden. Bitte halten Sie sich im Abflugbereich nahe dem Gate B12 auf. Wir informieren Sie, sobald neue Informationen vorliegen.", statement: "Der Flug nach London verspätet sich wegen schlechter Wetterbedingungen.", correctAnswer: "Richtig" },
          { id: 59, speaker: "Ansage 4", audioScript: "Und hier die Wetteraussichten für das Wochenende. Nach einem bewölkten Freitag erwartet uns am Samstag strahlender Sonnenschein in ganz Deutschland mit Temperaturen bis zu 28 Grad. Am Sonntag kühlt es sich jedoch wieder ab und es ist vermehrt mit Gewittern zu rechnen.", statement: "Am Sonntag wird das Wetter deutlich schöner als am Samstag.", correctAnswer: "Falsch" },
          { id: 60, speaker: "Ansage 5", audioScript: "Liebe Kundinnen und Kunden. Bitte beachten Sie unsere Sonderaktion im Erdgeschoss. Nur heute erhalten Sie auf alle Koffer und Reisetaschen der Marke Voyager einen Rabatt von 20 Prozent. Kommen Sie vorbei und sichern Sie sich Ihr Schnäppchen vor dem nächsten Urlaub.", statement: "Der Rabatt auf Reisegepäck gilt exklusiv für Inhaber einer Kundenkarte.", correctAnswer: "Falsch" }
        ]
      }
    ]
  },

  // ==================== TEST SET 2 ====================
  {
    setId: 2,
    parts: [
      {
        part: "Teil 1",
        title: "Hörverstehen (Globalverstehen)",
        description: "Sie hören fünf kurze Aussagen von verschiedenen Personen zu einem Thema. Entscheiden Sie bei den Aufgaben 41-45, ob die jeweilige Aussage Richtig oder Falsch ist. Sie hören die Aussagen nur einmal.",
        topic: "Thema: E-Learning und Online-Studium",
        items: [
          { id: 41, speaker: "Sprecher 1", audioScript: "Für mich ist das Online-Studium ein absoluter Segen. Ich kann mir meine Zeit frei einteilen, arbeiten gehen und lernen, wann es mir am besten passt. Ich muss nicht jeden Tag stundenlang zur Uni pendeln und spare dadurch viel Zeit und Geld für Bahntickets.", statement: "Sprecher 1 sieht im Online-Studium vor allem Vorteile bei der Flexibilität und der Ersparnis von Reisezeit.", correctAnswer: "Richtig" },
          { id: 42, speaker: "Sprecher 2", audioScript: "Mir fehlt beim E-Learning einfach der persönliche Kontakt. Vor dem Bildschirm lernt man einsam vor sich hin. Man kann sich nicht mal schnell mit Kommilitonen in der Pause austauschen oder gemeinsam in der Bibliothek lernen. Der soziale Aspekt eines Studiums geht völlig verloren.", statement: "Sprecher 2 bedauert den Mangel an sozialer Interaktion beim Online-Lernen.", correctAnswer: "Richtig" },
          { id: 43, speaker: "Sprecher 3", audioScript: "Es erfordert eine enorme Selbstdisziplin. Zu Hause gibt es einfach zu viele Ablenkungen: die Wäsche, der Fernseher oder das Smartphone. Ich merke, dass ich ohne den festen Stundenplan einer Präsenzuni viel langsamer vorankomme und oft Aufgaben aufschiebe.", statement: "Sprecher 3 fällt es leicht, sich zu Hause ohne feste Vorgaben zu organisieren.", correctAnswer: "Falsch" },
          { id: 44, speaker: "Sprecher 4", audioScript: "Viele Dozenten sind technisch überhaupt nicht auf der Höhe. Die Vorlesungen werden oft nur lieblos als PDF hochgeladen oder die Verbindung in den Videokonferenzen bricht ständig ab. Bevor man E-Learning flächendeckend einführt, müsste erst die Infrastruktur an den Unis verbessert werden.", statement: "Sprecher 4 bemängelt die technische Umsetzung und Kompetenz der Lehrkräfte.", correctAnswer: "Richtig" },
          { id: 45, speaker: "Sprecher 5", audioScript: "Eine Mischung aus beidem wäre ideal. Die Theorievorlesungen kann man sich doch prima online ansehen, wann man will. Aber für praktische Übungen, Seminare und Gruppenarbeiten sollte man sich auf jeden Fall persönlich an der Hochschule treffen. Reine Online-Angebote reichen nicht aus.", statement: "Sprecher 5 wünscht sich ein rein digitales Studienmodell ohne jegliche Präsenztermine.", correctAnswer: "Falsch" }
        ]
      },
      {
        part: "Teil 2",
        title: "Hörverstehen (Detailverstehen)",
        description: "Sie hören ein Gespräch oder Interview. Wählen Sie bei den Aufgaben 46-55 die richtige Antwort (a, b oder c). Sie hören den Text nur einmal.",
        topic: "Interview: Gesunde Ernährung und Bio-Lebensmittel",
        audioScript: "Moderator: Guten Tag zu unserem wöchentlichen Magazin 'Ernährung Heute'. Wir sprechen heute mit dem Ernährungsberater Herrn Jan Becker. Herr Becker, immer mehr Menschen kaufen Bio-Produkte. Sind diese tatsächlich gesünder?\n\nBecker: Guten Tag. Die kurze Antwort lautet: Ja, aber man muss differenzieren. Bio-Lebensmittel enthalten nachweislich weniger Pestizidrückstände und oft mehr sekundäre Pflanzenstoffe. Allerdings macht allein der Stempel 'Bio' ein produkt noch nicht gesund. Ein Bio-Keks enthält immer noch viel Zucker und Fett und ist nicht gesünder als ein normaler Apfel.\n\nModerator: Bio-Produkte sind oft erheblich teurer. Lohnt sich der Aufpreis denn wirklich?\n\nBecker: Für die Umwelt lohnt es sich in jedem Fall, da die ökologische Landwirtschaft den Boden schont und die Artenvielfalt fördert. Wer Geld sparen möchte, sollte vor allem regional und saisonal einkaufen. Ein heimischer Apfel aus konventionellem Anbau in der Saison hat oft eine bessere Ökobilanz als eine Bio-Erdbeere, die im Winter aus Südamerika eingeflogen werden muss.\n\nModerator: Viele Verbraucher sind verwirrt durch die Vielzahl an verschiedenen Bio-Siegeln. Worauf sollte man achten?\n\nBecker: Das stimmt, es ist unübersichtlich. Das EU-Bio-Siegel ist der gesetzliche Mindeststandard. Deutlich strengere Kriterien bezüglich Tierhaltung und Düngung haben jedoch die Verbände wie Demeter, Bioland oder Naturland. Wer also Wert auf maximalen Umweltschutz legt, sollte auf diese Logos achten.\n\nModerator: Herr Becker, vielen Dank für das informative Gespräch.",
        questions: [
          { id: 46, question: "Wer ist Jan Becker?", options: [{ id: "a", text: "Ein Bio-Landwirt." }, { id: "b", text: "Ein Ernährungsberater." }, { id: "c", text: "Ein Tester für Lebensmittelsicherheit." }], correctAnswer: "b" },
          { id: 47, question: "Was sagt Herr Becker über den gesundheitlichen Wert von Bio-Lebensmitteln?", options: [{ id: "a", text: "Sie enthalten weniger Schadstoffe, sind aber nicht automatisch kalorienarm." }, { id: "b", text: "Sie sind in jedem Fall ungesünder als konventionelle Ware." }, { id: "c", text: "Sie heilen nachweislich Krankheiten." }], correctAnswer: "a" },
          { id: 48, question: "Welchen Nutzen hat der Kauf von Bio-Produkten laut Becker für die Umwelt?", options: [{ id: "a", text: "Er verhindert jeglichen Verpackungsmüll." }, { id: "b", text: "Er schont die Böden und fördert die Vielfalt der Arten." }, { id: "c", text: "Er stoppt den weltweiten Klimawandel sofort." }], correctAnswer: "b" },
          { id: 49, question: "Wie kann man sich laut Becker preiswert und umweltschonend ernähren?", options: [{ id: "a", text: "Indem man nur noch importierte Bio-Produkte kauft." }, { id: "b", text: "Indem man Lebensmittel kauft, die in der Region und zur passenden Jahreszeit wachsen." }, { id: "c", text: "Indem man möglichst wenig Obst und Gemüse isst." }], correctAnswer: "b" },
          { id: 50, question: "Welchen Vergleich zieht Becker bei der Ökobilanz?", options: [{ id: "a", text: "Eine konventionelle Erdbeere ist immer besser als eine Bio-Erdbeere." }, { id: "b", text: "Ein regionaler Saison-Apfel kann umweltfreundlicher sein als eingeflogenes Bio-Obst." }, { id: "c", text: "Flugzeuge verbrauchen weniger Benzin als Lkws." }], correctAnswer: "b" },
          { id: 51, question: "Was stellt die Verbraucher laut Moderator vor Herausforderungen?", options: [{ id: "a", text: "Die schlechte Verfügbarkeit von Obst." }, { id: "b", text: "Die Vielzahl unterschiedlicher Bio-Siegel." }, { id: "c", text: "Das Fehlen jeglicher Kontrollen." }], correctAnswer: "b" },
          { id: 52, question: "Was ist das EU-Bio-Siegel?", options: [{ id: "a", text: "Das strengste Siegel auf dem deutschen Markt." }, { id: "b", text: "Der gesetzlich vorgeschriebene Mindeststandard für Bio-Waren." }, { id: "c", text: "Ein Siegel, das ausschließlich für Fleischwaren gilt." }], correctAnswer: "b" },
          { id: 53, question: "Welche Siegel haben strengere Vorschriften als der EU-Standard?", options: [{ id: "a", text: "Die Siegel von Verbänden wie Bioland oder Demeter." }, { id: "b", text: "Jedes Siegel aus dem außereuropäischen Ausland." }, { id: "c", text: "Es gibt keine strengeren Siegel." }], correctAnswer: "a" },
          { id: 54, question: "Warum sollte man laut Becker Bio-Kekse kritisch sehen?", options: [{ id: "a", text: "Weil sie extrem bitter schmecken." }, { id: "b", text: "Weil sie trotz 'Bio' viel Zucker und Fett enthalten." }, { id: "c", text: "Weil sie oft giftige Stoffe enthalten." }], correctAnswer: "b" },
          { id: 55, question: "Worauf bezieht sich die strengere Richtlinie deutscher Bio-Verbände besonders?", options: [{ id: "a", text: "Auf die Verpackungsgrößen." }, { id: "b", text: "Auf Aspekte der Tierhaltung und den Einsatz von Düngemitteln." }, { id: "c", text: "Auf die Transportwege der Lkws." }], correctAnswer: "b" }
        ]
      },
      {
        part: "Teil 3",
        title: "Hörverstehen (Selektives Verstehen)",
        description: "Sie hören fünf kurze Ansagen (z.B. im Radio oder an Bahnhöfen). Entscheiden Sie bei den Aufgaben 56-60, ob die Aussage Richtig oder Falsch ist. Sie hören die Ansagen nur einmal.",
        items: [
          { id: 56, speaker: "Ansage 1", audioScript: "Meine Damen und Herren an Gleis 11. Bitte beachten Sie: Der Regionalexpress RE 4 nach Stuttgart Hauptbahnhof, Abfahrt 16:30 Uhr, fällt heute wegen einer technischen Störung am Zug komplett aus. Fahrgäste nach Stuttgart nutzen bitte die S-Bahn-Linie S1 auf Gleis 2, Abfahrt um 16:45 Uhr.", statement: "Der Regionalexpress nach Stuttgart hat heute eine erhebliche Verspätung.", correctAnswer: "Falsch" },
          { id: 57, speaker: "Ansage 2", audioScript: "Wir unterbrechen das Programm für eine wichtige Verkehrsmeldung auf der A3 Köln Richtung Frankfurt. Zwischen Limburg-Nord und Bad Camberg befindet sich eine ungesicherte Unfallstelle auf der linken Spur. Bitte fahren Sie in diesem Bereich äußerst vorsichtig und überholen Sie nicht.", statement: "Autofahrer auf der A3 sollen auf der linken Spur vorsichtig überholen.", correctAnswer: "Falsch" },
          { id: 58, speaker: "Ansage 3", audioScript: "Sehr geehrte Fluggäste des Fluges X3 2104 nach Mallorca. Die Sicherheitskontrollen im Terminal A sind derzeit stark überlastet. Um Ihren Flug nicht zu verpassen, bitten wir alle Passagiere dieses Fluges, sich unverzüglich zur Sicherheitskontrolle zu begeben, auch wenn Sie noch kein Gepäck aufgegeben haben.", statement: "Die Fluggäste nach Mallorca sollen sich sofort zur Sicherheitskontrolle begeben.", correctAnswer: "Richtig" },
          { id: 59, speaker: "Ansage 4", audioScript: "Hier ist der Wetterbericht für das Bundesland Hessen. Am heutigen Nachmittag bleibt es heiter und trocken bei Werten um 22 Grad. Morgen zieht jedoch von Westen her ein Regengebiet auf, das erhebliche Niederschläge und einen Temperatursturz auf 15 Grad mit sich bringt. Erst am Sonntag wird es wieder milder.", statement: "Für den morgigen Tag wird regnerisches und kühleres Wetter vorhergesagt.", correctAnswer: "Richtig" },
          { id: 60, speaker: "Ansage 5", audioScript: "Liebe Besucher des städtischen Zoos. In wenigen Minuten, um 15 Uhr, beginnt die Fütterung der Robben am großen Außenbecken. Unser Tierpfleger wird Ihnen dabei spannende Details über die Lebensweise dieser Tiere erzählen. Wir wünschen Ihnen viel Spaß.", statement: "Die Fütterung der Tiere findet ohne Erklärungen statt.", correctAnswer: "Falsch" }
        ]
      }
    ]
  },

  // ==================== TEST SET 3 ====================
  {
    setId: 3,
    parts: [
      {
        part: "Teil 1",
        title: "Hörverstehen (Globalverstehen)",
        description: "Sie hören fünf kurze Aussagen von verschiedenen Personen zu einem Thema. Entscheiden Sie bei den Aufgaben 41-45, ob die jeweilige Aussage Richtig oder Falsch ist. Sie hören die Aussagen nur einmal.",
        topic: "Thema: Homeoffice vs. Büropräsenz",
        items: [
          { id: 41, speaker: "Sprecher 1", audioScript: "Seit ich drei Tage pro Woche im Homeoffice arbeite, bin ich viel entspannter. Ich spare mir den morgendlichen Stress auf der Autobahn und kann in meinen Pausen mal schnell einkaufen oder die Waschmaschine anmachen. Ich arbeite zu Hause auch viel konzentrierter, weil mich niemand im Büro stört.", statement: "Sprecher 1 empfindet das Homeoffice als stressreduzierend und produktiver.", correctAnswer: "Richtig" },
          { id: 42, speaker: "Sprecher 2", audioScript: "Ich brauche die klare Trennung von Arbeit und Freizeit. Wenn mein Laptop auf dem Esstisch steht, neigt man dazu, auch abends um 21 Uhr noch schnell E-Mails zu beantworten. Im Büro klappe ich den Rechner um 17 Uhr zu und habe Feierabend. Das tut meiner psychischen Gesundheit besser.", statement: "Sprecher 2 findet es im Homeoffice leicht, Arbeit und Privatleben voneinander abzugrenzen.", correctAnswer: "Falsch" },
          { id: 43, speaker: "Sprecher 3", audioScript: "Der Flurfunk und der kurze Austausch mit Kollegen sind extrem wichtig, um Projekte voranzubringen. Per Video-Call bespricht man nur das Nötigste, aber die besten Ideen entstehen oft spontan beim gemeinsamen Mittagessen. Deshalb bin ich für eine feste Präsenzpflicht im Betrieb.", statement: "Sprecher 3 betont den Wert informeller persönlicher Kontakte für die Arbeit.", correctAnswer: "Richtig" },
          { id: 44, speaker: "Sprecher 4", audioScript: "Als Arbeitgeber konnte ich durch das Homeoffice-Modell unsere Bürofläche um die Hälfte verkleinern. Das spart uns monatlich Tausende Euro an Miete und Energiekosten. Unsere Mitarbeiter teilen sich nun die verbliebenen Schreibtische flexibel auf, was hervorragend funktioniert.", statement: "Sprecher 4 berichtet von finanziellen Einsparungen für das Unternehmen durch Homeoffice.", correctAnswer: "Richtig" },
          { id: 45, speaker: "Sprecher 5", audioScript: "Nicht jeder hat zu Hause ein eigenes Arbeitszimmer. Wenn man mit drei Kindern in einer kleinen Wohnung lebt und am Küchentisch arbeiten muss, ist Homeoffice kein Privileg, sondern eine Qual. Für solche Mitarbeiter muss es immer ein Angebot geben, im Büro zu arbeiten.", statement: "Sprecher 5 meint, dass das Homeoffice für alle Arbeitnehmer unter allen Umständen die beste Lösung ist.", correctAnswer: "Falsch" }
        ]
      },
      {
        part: "Teil 2",
        title: "Hörverstehen (Detailverstehen)",
        description: "Sie hören ein Gespräch oder Interview. Wählen Sie bei den Aufgaben 46-55 die richtige Antwort (a, b oder c). Sie hören den Text nur einmal.",
        topic: "Interview: Klimafreundliche Stadtentwicklung",
        audioScript: "Moderator: Willkommen zu unserem Forum 'Stadt der Zukunft'. Bei uns ist heute Herr Thomas Lang, Stadtplaner aus Hamburg. Herr Lang, Großstädte leiden im Sommer zunehmend unter extremer Hitze. Wie können wir das Problem lösen?\n\nLang: Guten Tag. Das Hauptproblem ist die sogenannte 'Versiegelung': Asphalt und Beton speichern die Hitze und lassen kein Wasser versickern. Wir müssen Städte grüner machen. Das bedeutet nicht nur Parks anzulegen, sondern auch Dächer und Fassaden von Gebäuden systematisch zu bepflanzen. Pflanzen kühlen die Luft durch Verdunstung massiv ab.\n\nModerator: Klingt gut, aber Hausbesitzer klagen oft über die hohen Kosten einer Fassadenbegrünung und die Gefahr von Bauschäden. Ist das berechtigt?\n\nLang: Moderne Systeme sind bautechnisch absolut sicher, wenn sie vom Fachmann installiert werden. Die Kosten sind anfangs hoch, ja. Aber man spart langfristig Energiekosten für Klimaanlagen im Sommer und Heizkosten im Winter, da die Pflanzen wie eine natürliche Dämmschicht wirken. Zudem bieten viele Städte finanzielle Förderprogramme an.\n\nModerator: Ein weiteres Thema ist der Verkehr. Wie sieht eine klimafreundliche Mobilität in der Stadt aus?\n\nLang: Wir müssen den Autoverkehr drastisch reduzieren. Das gelingt nur, wenn wir den ÖPNV und das Radwegenetz massiv ausbauen und attraktiver machen. Radwege müssen baulich von der Straße getrennt sein, damit sich auch Kinder und ältere Menschen sicher fühlen. In Kopenhagen funktioniert das seit Jahrzehnten vorbildlich.\n\nModerator: Herr Lang, vielen Dank für Ihre Ausführungen.",
        questions: [
          { id: 46, question: "Welchen Beruf übt Thomas Lang aus?", options: [{ id: "a", text: "Architekt für Einfamilienhäuser." }, { id: "b", text: "Stadtplaner." }, { id: "c", text: "Vertreter einer Umweltbehörde." }], correctAnswer: "b" },
          { id: 47, question: "Warum werden Städte im Sommer besonders heiß?", options: [{ id: "a", text: "Weil es dort zu viele Autos gibt." }, { id: "b", text: "Weil Asphalt und Beton die Wärme speichern und keine Verdunstung stattfindet." }, { id: "c", text: "Weil in den Städten weniger Wind weht." }], correctAnswer: "b" },
          { id: 48, question: "Welche Maßnahme schlägt der Experte gegen die Hitze vor?", options: [{ id: "a", text: "Die Straßen weiß anzumalen." }, { id: "b", text: "Systematische Bepflanzung von Dächern, Fassaden und Freiflächen." }, { id: "c", text: "Den Einbau von Klimaanlagen in jedem Zimmer vorzuschreiben." }], correctAnswer: "b" },
          { id: 49, question: "Welche Bedenken haben manche Hausbesitzer bezüglich der Fassadenbegrünung?", options: [{ id: "a", text: "Dass die Pflanzen im Winter erfrieren." }, { id: "b", text: "Mögliche Bauschäden und hohe Anschaffungskosten." }, { id: "c", text: "Dass das Haus dadurch an Wert verliert." }], correctAnswer: "b" },
          { id: 50, question: "Wie können Pflanzen am Gebäude Energiekosten sparen?", options: [{ id: "a", text: "Sie erzeugen Solarstrom." }, { id: "b", text: "Sie wirken als natürliche Isolierung im Sommer wie im Winter." }, { id: "c", text: "Sie reinigen das Regenwasser für die Heizung." }], correctAnswer: "b" },
          { id: 51, question: "Wie unterstützen Kommunen die Hausbesitzer?", options: [{ id: "a", text: "Durch kostenlose Beratung und finanzielle Zuschüsse." }, { id: "b", text: "Sie übernehmen die gesamte Pflege der Pflanzen." }, { id: "c", text: "Gar nicht, der Umbau ist komplett privat zu zahlen." }], correctAnswer: "a" },
          { id: 52, question: "Was ist laut Lang eine Bedingung für klimafreundlichen Verkehr?", options: [{ id: "a", text: "Der Ausbau von mehrspurigen Straßen." }, { id: "b", text: "Die deutliche Reduzierung des privaten Autoverkehrs." }, { id: "c", text: "Die Abschaffung des öffentlichen Personennahverkehrs." }], correctAnswer: "b" },
          { id: 53, question: "Wie sollten Radwege gestaltet sein, damit sie sicher sind?", options: [{ id: "a", text: "Als einfache weiße Linie auf der Fahrbahn." }, { id: "b", text: "Baulich getrennt vom Autoverkehr." }, { id: "c", text: "Sie sollten nur für Sportler freigegeben werden." }], correctAnswer: "b" },
          { id: 54, question: "Welche Stadt wird als positives Beispiel für Radwege genannt?", options: [{ id: "a", text: "Hamburg." }, { id: "b", text: "Kopenhagen." }, { id: "c", text: "München." }], correctAnswer: "b" },
          { id: 55, question: "Welchen Nutzen hat die Fassadenbegrünung laut Thomas Lang neben der Dämmung?", options: [{ id: "a", text: "Sie zieht Vögel und Insekten an, was gut für die Natur ist." }, { id: "b", text: "Es gibt keinen weiteren Nutzen." }, { id: "c", text: "Sie kühlt das Umfeld durch die Verdunstung von Wasser ab." }], correctAnswer: "c" }
        ]
      },
      {
        part: "Teil 3",
        title: "Hörverstehen (Selektives Verstehen)",
        description: "Sie hören fünf kurze Ansagen (z.B. im Radio oder an Bahnhöfen). Entscheiden Sie bei den Aufgaben 56-60, ob die Aussage Richtig oder Falsch ist. Sie hören die Ansagen nur einmal.",
        items: [
          { id: 56, speaker: "Ansage 1", audioScript: "Sehr geehrte Besucher der Gemäldegalerie. Der Ausstellungsraum 3 mit den Werken des Impressionismus ist wegen Renovierungsarbeiten heute ab 12 Uhr für den Publikumsverkehr gesperrt. Die Sonderausstellung im Obergeschoss steht Ihnen jedoch weiterhin uneingeschränkt zur Verfügung. Wir danken für Ihr Verständnis.", statement: "Die impressionistischen Gemälde können heute Nachmittag nicht besichtigt werden.", correctAnswer: "Richtig" },
          { id: 57, speaker: "Ansage 2", audioScript: "Fahrgästegruppe am Gleis 2, bitte beachten Sie: Der Regionalzug nach Frankfurt, geplante Abfahrt um 18 Uhr, hat derzeit eine unbestimmte Verspätung aufgrund eines Notarzteinsatzes auf der Strecke. Wir bitten Sie, auf die Regionalbahn um 18:20 Uhr auszuweichen. Ihre Fahrkarten sind für diesen Zug ebenfalls gültig.", statement: "Fahrgäste nach Frankfurt müssen ein neues Ticket für den Ersatzzug kaufen.", correctAnswer: "Falsch" },
          { id: 58, speaker: "Ansage 3", audioScript: "Achtung an alle Badegäste am Silbersee. Wegen akuter Blaualgenentwicklung im Uferbereich hat das Gesundheitsamt mit sofortiger Wirkung ein absolutes Badeverbot erlassen. Das Betreten des Wassers ist gesundheitsgefährdend und untersagt. Die Liegewiesen dürfen jedoch weiterhin genutzt werden.", statement: "Am Silbersee darf ab sofort nicht mehr im Wasser geschwommen werden.", correctAnswer: "Richtig" },
          { id: 59, speaker: "Ansage 4", audioScript: "Und nun zum Sport. Wegen der anhaltenden Regenfälle und der Unbespielbarkeit des Rasens im Stadion wird das für heute Abend angesetzte Halbfinalspiel der Fußball-Regionalliga zwischen dem FC Bayern-Hof und Turbine Dresden auf kommenden Mittwoch verschoben. Tickets behalten ihre Gültigkeit.", statement: "Das Fußballspiel findet heute Abend trotz des schlechten Wetters statt.", correctAnswer: "Falsch" },
          { id: 60, speaker: "Ansage 5", audioScript: "Sehr geehrte Kunden. An unserer Information im Kassenbereich liegt ein Autoschlüssel der Marke Volkswagen, der auf dem Parkplatz gefunden wurde. Der Besitzer wird gebeten, sich unter Angabe der Details bei unseren Mitarbeitern zu melden. Vielen Dank.", statement: "Ein Kunde hat auf dem Parkplatz seinen Autoschlüssel verloren.", correctAnswer: "Richtig" }
        ]
      }
    ]
  },

  // ==================== TEST SET 4 ====================
  {
    setId: 4,
    parts: [
      {
        part: "Teil 1",
        title: "Hörverstehen (Globalverstehen)",
        description: "Sie hören fünf kurze Aussagen von verschiedenen Personen zu einem Thema. Entscheiden Sie bei den Aufgaben 41-45, ob die jeweilige Aussage Richtig oder Falsch ist. Sie hören die Aussagen nur einmal.",
        topic: "Thema: Erhöhung der Ticketpreise für den ÖPNV",
        items: [
          { id: 41, speaker: "Sprecher 1", audioScript: "Es ist unverschämt, dass die Fahrkarten schon wieder teurer werden. Ständig gibt es Verspätungen, die Waggons sind dreckig und überfüllt, und im Sommer fällt die Klimaanlage aus. Für so einen schlechten Service sollte man eigentlich weniger bezahlen, nicht mehr!", statement: "Sprecher 1 kritisiert die Erhöhung der Preise wegen der mangelhaften Qualität des ÖPNV.", correctAnswer: "Richtig" },
          { id: 42, speaker: "Sprecher 2", audioScript: "Wir müssen die Verkehrswende finanzieren. Neue Busse, die Sanierung von Gleisen und faire Löhne für die Fahrer kosten nun einmal Geld. Wenn wir einen modernen und zuverlässigen Nahverkehr wollen, müssen wir auch bereit sein, einen angemessenen Preis dafür zu bezahlen.", statement: "Sprecher 2 hält Preisanpassungen für notwendig, um die Infrastruktur zu modernisieren.", correctAnswer: "Richtig" },
          { id: 43, speaker: "Sprecher 3", audioScript: "Wenn die Tickets teurer werden, steigen viele Menschen wieder aufs Auto um. Das ist genau das falsche Signal für den Umweltschutz. Der Staat sollte den Nahverkehr viel stärker subventionieren, damit die Tickets billig bleiben oder sogar kostenlos werden.", statement: "Sprecher 3 befürchtet negative ökologische Folgen durch teurere Tickets.", correctAnswer: "Richtig" },
          { id: 44, speaker: "Sprecher 4", audioScript: "Für Rentner, Schüler und Geringverdiener sind die neuen Preise kaum noch bezahlbar. Die Mobilität ist ein Grundrecht und darf nicht vom Geldbeutel abhängen. Es muss zumindest deutlich günstigere Sozialtickets für diese Gruppen geben.", statement: "Sprecher 4 fordert einkommensunabhängige Ermäßigungen für bestimmte Personengruppen.", correctAnswer: "Richtig" },
          { id: 45, speaker: "Sprecher 5", audioScript: "Ich nutze den ÖPNV nur selten und fahre meistens mit dem Rad. Aber wenn ich mal ein Ticket brauche, finde ich den Preis okay. Man spart sich ja schließlich auch die Parkplatzsuche und die teuren Benzinpreise. Da zahle ich gerne vier Euro für eine Einzelfahrt.", statement: "Sprecher 5 meint, dass Autofahren in der Stadt billiger ist als die Nutzung öffentlicher Verkehrsmittel.", correctAnswer: "Falsch" }
        ]
      },
      {
        part: "Teil 2",
        title: "Hörverstehen (Detailverstehen)",
        description: "Sie hören ein Gespräch oder Interview. Wählen Sie bei den Aufgaben 46-55 die richtige Antwort (a, b oder c). Sie hören den Text nur einmal.",
        topic: "Interview: Die Zukunft des Buchmarkts und E-Books",
        audioScript: "Moderator: Herzlich willkommen bei 'Kultur Aktuell'. Heute sprechen wir mit Dr. Jürgen Schulz, Branchenanalyst und Experte für die Buchindustrie. Herr Dr. Schulz, verdrängen E-Books das gedruckte Buch in naher Zukunft komplett?\n\nDr. Schulz: Guten Tag. Das wurde vor zehn Jahren oft prophezeit, hat sich aber nicht bewahrheitet. Der E-Book-Markt hat sich in Deutschland bei einem Anteil von etwa 5 bis 8 Prozent stabilisiert. Das gedruckte Buch ist nach wie vor der klare Favorit der Leser. Die Menschen lieben das haptische Gefühl, ein echtes Buch in den Händen zu halten.\n\nModerator: Welche Vorteile schätzen denn die Käufer von E-Books besonders?\n\nDr. Schulz: Vor allem das geringe Gewicht und die Platzersparnis, was besonders auf Reisen unschlagbar ist. Zudem kann man die Schriftgröße anpassen, was älteren Menschen sehr hilft. Auch der Kauf geht in Sekundenschnelle per Download.\n\nModerator: Der Buchhandel vor Ort steht dennoch unter Druck, vor allem durch den Online-Giganten Amazon. Wie können kleine Buchhandlungen überleben?\n\nDr. Schulz: Sie müssen sich spezialisieren und auf persönliche Beratung setzen. Ein Online-Algorithmus kann ein persönliches Gespräch nicht ersetzen. Viele Buchhändler organisieren Lesungen, Weinabende oder bieten gemütliche Cafés an, um den Laden zu einem sozialen Treffpunkt zu machen. Kunden schätzen diese Atmosphäre und kaufen dann auch bewusst lokal.\n\nModerator: Herr Dr. Schulz, vielen Dank für das Gespräch.",
        questions: [
          { id: 46, question: "Wer ist Dr. Jürgen Schulz?", options: [{ id: "a", text: "Ein Buchautor." }, { id: "b", text: "Ein Branchenanalyst für den Buchmarkt." }, { id: "c", text: "Der Besitzer eines Verlags." }], correctAnswer: "b" },
          { id: 47, question: "Wie hoch ist der Marktanteil von E-Books in Deutschland in etwa?", options: [{ id: "a", text: "Er liegt stabil zwischen 5 und 8 Prozent." }, { id: "b", text: "Er macht bereits über 50 Prozent aus." }, { id: "c", text: "Er sinkt kontinuierlich gegen Null." }], correctAnswer: "a" },
          { id: 48, question: "Was schätzen Leser laut Schulz besonders am gedruckten Buch?", options: [{ id: "a", text: "Das haptische Gefühl beim Halten des Buches." }, { id: "b", text: "Dass es billiger ist als die digitale Version." }, { id: "c", text: "Dass man es im Dunkeln ohne Lampe lesen kann." }], correctAnswer: "b" },
          { id: 49, question: "Welchen Vorteil bieten E-Books auf Reisen?", options: [{ id: "a", text: "Sie verbrauchen überhaupt keinen Strom." }, { id: "b", text: "Sie sind extrem leicht und sparen viel Platz im Gepäck." }, { id: "c", text: "Man bekommt sie im Ausland geschenkt." }], correctAnswer: "b" },
          { id: 50, question: "Für welche Gruppe sind E-Books laut Schulz aufgrund der Schriftgrößenanpassung hilfreich?", options: [{ id: "a", text: "Für Kinder beim Lesenlernen." }, { id: "b", text: "Für ältere Menschen mit Sehschwierigkeiten." }, { id: "c", text: "Für Studenten bei Prüfungen." }], correctAnswer: "b" },
          { id: 51, question: "Wer setzt den lokalen Buchhandel besonders unter Druck?", options: [{ id: "a", text: "Die Bibliotheken." }, { id: "b", text: "Große Online-Händler wie Amazon." }, { id: "c", text: "Die Autoren selbst." }], correctAnswer: "b" },
          { id: 52, question: "Wie können kleine Buchhandlungen laut Dr. Schulz überleben?", options: [{ id: "a", text: "Durch Spezialisierung, persönliche Beratung und Event-Angebote." }, { id: "b", text: "Sie müssen sich gesetzlich absichern lassen." }, { id: "c", text: "Indem sie nur noch E-Books verkaufen." }], correctAnswer: "a" },
          { id: 53, question: "Was kann ein Online-Algorithmus nicht ersetzen?", options: [{ id: "a", text: "Das persönliche Beratungsgespräch von Mensch zu Mensch." }, { id: "b", text: "Die schnelle Lieferung der Ware." }, { id: "c", text: "Den Schreibprozess des Autors." }], correctAnswer: "a" },
          { id: 54, question: "Welche Veranstaltungen helfen lokalen Buchhandlungen?", options: [{ id: "a", text: "Sportkurse im Laden." }, { id: "b", text: "Autorenlesungen, Weinabende und Café-Konzepte." }, { id: "c", text: "Kochkurse für asiatische Küche." }], correctAnswer: "b" },
          { id: 55, question: "Warum kaufen Kunden laut Schulz bewusst vor Ort?", options: [{ id: "a", text: "Weil sie keine Pakete empfangen möchten." }, { id: "b", text: "Wegen der besonderen Atmosphäre und um den lokalen Handel zu unterstützen." }, { id: "c", text: "Weil es im Internet keine Bücher mehr gibt." }], correctAnswer: "b" }
        ]
      },
      {
        part: "Teil 3",
        title: "Hörverstehen (Selektives Verstehen)",
        description: "Sie hören fünf kurze Ansagen (z.B. im Radio oder an Bahnhöfen). Entscheiden Sie bei den Aufgaben 56-60, ob die Aussage Richtig oder Falsch ist. Sie hören die Ansagen nur einmal.",
        items: [
          { id: 56, speaker: "Ansage 1", audioScript: "Sehr geehrte Theaterbesucher. Wir bitten Sie, vor Beginn der Vorstellung Ihre Mobiltelefone vollständig auszuschalten. Das Fotografieren und Filmen während der Aufführung ist aus urheberrechtlichen Gründen strengstens untersagt. Wir danken Ihnen für Ihre Kooperation.", statement: "Während des Theaterstücks ist das Aufnehmen von Videos verboten.", correctAnswer: "Richtig" },
          { id: 57, speaker: "Ansage 2", audioScript: "Verkehrsbehinderung auf der A1 Bremen Richtung Hamburg. Nach einem Lkw-Unfall zwischen Sittensen und Elsdorf ist die Fahrbahn derzeit komplett gesperrt. Der Verkehr wird ab Sittensen umgeleitet. Es hat sich bereits ein Stau von zehn Kilometern Länge gebildet.", statement: "Auf der A1 kann man trotz des Unfalls langsam an der Unfallstelle vorbeifahren.", correctAnswer: "Falsch" },
          { id: 58, speaker: "Ansage 3", audioScript: "Achtung an alle Fahrgäste der Bodenseefähre nach Konstanz. Wegen stürmischer Winde und starkem Wellengang ist der Fährbetrieb für den heutigen Nachmittag vorübergehend eingestellt. Der nächste reguläre Abfahrtsversuch findet morgen früh um 7 Uhr statt. Wir bitten um Entschuldigung.", statement: "Die Fähre nach Konstanz fährt heute wegen des schlechten Wetters nicht mehr.", correctAnswer: "Richtig" },
          { id: 59, speaker: "Ansage 4", audioScript: "Hier ist der Pollenflug-Gefahrenindex für das Wochenende. Durch das anhaltend trockene und windige Wetter ist im gesamten Bundesgebiet mit einem extrem starken Flug von Birken- und Gräserpollen zu rechnen. Allergikern wird empfohlen, längere Aufenthalte im Freien in den Mittagsstunden zu vermeiden.", statement: "Allergiker sollten am Wochenende vor allem am Mittag draußen vorsichtig sein.", correctAnswer: "Richtig" },
          { id: 60, speaker: "Ansage 5", audioScript: "Sehr geehrte Besucher der städtischen Museen. Bitte beachten Sie unsere veränderten Öffnungszeiten während der Feiertage. Am kommenden Pfingstmontag bleiben alle städtischen Ausstellungen und Museen für Besucher geschlossen. Ab Dienstag gelten wieder die gewohnten Zeiten.", statement: "Die Museen haben am Pfingstmontag wie an jedem normalen Wochentag geöffnet.", correctAnswer: "Falsch" }
        ]
      }
    ]
  },

  // ==================== TEST SET 5 ====================
  {
    setId: 5,
    parts: [
      {
        part: "Teil 1",
        title: "Hörverstehen (Globalverstehen)",
        description: "Sie hören fünf kurze Aussagen von verschiedenen Personen zu einem Thema. Entscheiden Sie bei den Aufgaben 41-45, ob die jeweilige Aussage Richtig oder Falsch ist. Sie hören die Aussagen nur einmal.",
        topic: "Thema: E-Scooter in der Stadt",
        items: [
          { id: 41, speaker: "Sprecher 1", audioScript: "Diese Dinger sind eine reine Katastrophe! Sie stehen überall im Weg herum, blockieren die Gehwege und sind brandgefährlich für Fußgänger, vor allem für ältere Menschen. Meiner Meinung nach sollten E-Scooter in den Innenstädten komplett verboten werden.", statement: "Sprecher 1 fordert ein vollständiges Verbot von E-Scootern in städtischen Zentren.", correctAnswer: "Richtig" },
          { id: 42, speaker: "Sprecher 2", audioScript: "Ich finde E-Scooter super praktisch. Wenn man es eilig hat, leiht man sich einfach einen für die letzte Meile von der U-Bahn zum Büro. Es geht schnell, ist unkompliziert und macht auch noch Spaß. Man muss sie nur ordentlich parken.", statement: "Sprecher 2 nutzt E-Scooter als praktische Ergänzung zum öffentlichen Nahverkehr.", correctAnswer: "Richtig" },
          { id: 43, speaker: "Sprecher 3", audioScript: "Man sollte die Nutzer viel strenger kontrollieren! Ständig sieht man Jugendliche zu zweit auf einem Roller fahren, natürlich ohne Helm und oft auf Gehwegen oder sogar in Fußgängerzonen. Wenn es keine harten Strafen gibt, ändert sich an dem Chaos leider gar nichts.", statement: "Sprecher 3 wünscht sich schärfere Kontrollen und Sanktionen für Fehlverhalten.", correctAnswer: "Richtig" },
          { id: 44, speaker: "Sprecher 4", audioScript: "Ökologisch gesehen bringen diese E-Scooter doch überhaupt nichts. Die meisten Fahrten ersetzen nicht das Auto, sondern Fußwege oder Fahrten mit der Straßenbahn. Zudem müssen die Akkus nachts mit Transportern eingesammelt werden, was wieder Abgase erzeugt.", statement: "Sprecher 4 bezweifelt den positiven Umweltnutzen von E-Scootern.", correctAnswer: "Richtig" },
          { id: 45, speaker: "Sprecher 5", audioScript: "Die Infrastruktur in unseren Städten ist einfach nicht für diese Fahrzeuge ausgelegt. Wir bräuchten viel breitere Radwege, auf denen sowohl Fahrräder als auch E-Scooter sicher aneinander vorbeikommen. Solange es diese Wege nicht gibt, bleibt die Unfallgefahr extrem hoch.", statement: "Sprecher 5 meint, dass E-Scooter-Fahrer unter allen Umständen Helme tragen sollten.", correctAnswer: "Falsch" }
        ]
      },
      {
        part: "Teil 2",
        title: "Hörverstehen (Detailverstehen)",
        description: "Sie hören ein Gespräch oder Interview. Wählen Sie bei den Aufgaben 46-55 die richtige Antwort (a, b oder c). Sie hören den Text nur einmal.",
        topic: "Interview: Die Rolle des Sports im Alltag",
        audioScript: "Moderator: Herzlich willkommen bei 'Gesund und Fit'. Heute im Studio ist der Sportwissenschaftler Dr. Marc Brand. Herr Dr. Brand, viele Menschen bewegen sich im Alltag viel zu wenig. Welchen Mindestaufwand empfehlen Sie?\n\nDr. Brand: Guten Tag. Die Weltgesundheitsorganisation empfiehlt mindestens 150 Minuten moderate Bewegung pro Woche. Das klingt viel, lässt sich aber leicht aufteilen: Zum Beispiel fünfmal pro Woche 30 Minuten zügiges Gehen oder Radfahren. Es geht nicht um Leistungssport, sondern um regelmäßige Aktivität.\n\nModerator: Viele klagen jedoch, dass sie nach der Arbeit keine Zeit oder Energie für Sport haben. Haben Sie da einen Tipp?\n\nDr. Brand: Absolut. Man muss Bewegung in den Alltag integrieren. Nehmen Sie die Treppe statt des Aufzugs, steigen Sie eine Station früher aus dem Bus aus oder machen Sie in der Mittagspause einen kleinen Spaziergang. Jedes bisschen Bewegung zählt und baut nachweislich Stress ab.\n\nModerator: Wie wichtig ist Sport eigentlich für das geistige Wohlbefinden?\n\nDr. Brand: Enorm wichtig! Bei körperlicher Aktivität schüttet der Körper Glückshormone wie Endorphine und Serotonin aus, während das Stresshormon Cortisol abgebaut wird. Sport hilft bei Schlafstörungen, beugt Depressionen vor und steigert die Konzentrationsfähigkeit im Beruf.\n\nModerator: Herr Dr. Brand, vielen Dank für diese Ratschläge.",
        questions: [
          { id: 46, question: "Wer ist Dr. Marc Brand?", options: [{ id: "a", text: "Ein Fitness-Trainer." }, { id: "b", text: "Ein Sportwissenschaftler." }, { id: "c", text: "Ein Arzt für Kardiologie." }], correctAnswer: "b" },
          { id: 47, question: "Wie viel Bewegung pro Woche empfiehlt die WHO laut Dr. Brand mindestens?", options: [{ id: "a", text: "Mindestens 150 Minuten moderate Aktivität." }, { id: "b", text: "Täglich mindestens zwei Stunden Intensivtraining." }, { id: "c", text: "Genau 45 Minuten pro Woche." }], correctAnswer: "a" },
          { id: 48, question: "Wie kann man die Bewegung laut Brand aufteilen?", options: [{ id: "a", text: "Indem man am Wochenende 3 Stunden joggt." }, { id: "b", text: "Fünfmal wöchentlich 30 Minuten zügiges Gehen." }, { id: "c", text: "Man sollte Sport ausschließlich abends machen." }], correctAnswer: "b" },
          { id: 49, question: "Welchen Tipp gibt der Experte für Schreibtischarbeiter im Alltag?", options: [{ id: "a", text: "Die Mittagspause komplett durchzuarbeiten." }, { id: "b", text: "Treppen statt Aufzüge zu nutzen und kurze Wege zu Fuß zu gehen." }, { id: "c", text: "Sich ein Laufband im Büro installieren zu lassen." }], correctAnswer: "b" },
          { id: 50, question: "Welche Hormone baut der Körper bei sportlicher Aktivität ab?", options: [{ id: "a", text: "Endorphine." }, { id: "b", text: "Das Stresshormon Cortisol." }, { id: "c", text: "Adrenalin." }], correctAnswer: "b" },
          { id: 51, question: "Wie wirkt sich Bewegung auf die Psyche aus?", options: [{ id: "a", text: "Sie führt oft zu starker Erschöpfung." }, { id: "b", text: "Sie steigert das Wohlbefinden, baut Stress ab und fördert guten Schlaf." }, { id: "c", text: "Sie hat keinerlei messbare Auswirkung auf den Geist." }], correctAnswer: "b" },
          { id: 52, question: "Welcher Sport wird im Interview als gute moderate Bewegung genannt?", options: [{ id: "a", text: "Marathontraining." }, { id: "b", text: "Zügiges Gehen oder Radfahren." }, { id: "c", text: "Gewichtheben im Studio." }], correctAnswer: "b" },
          { id: 53, question: "Warum fällt es vielen Menschen schwer, Sport zu treiben?", options: [{ id: "a", text: "Weil Sportanlagen zu teuer sind." }, { id: "b", text: "Wegen Zeitmangels und Energiemangels nach dem Arbeitstag." }, { id: "c", text: "Weil Sportgeräte verboten wurden." }], correctAnswer: "b" },
          { id: 54, question: "Welche kognitive Verbesserung wird am Ende genannt?", options: [{ id: "a", text: "Eine Steigerung der Konzentrationsfähigkeit im Beruf." }, { id: "b", text: "Ein besseres Sehvermögen." }, { id: "c", text: "Ein verbessertes mathematisches Verständnis." }], correctAnswer: "a" },
          { id: 55, question: "Was ist das Fazit des Interviews?", options: [{ id: "a", text: "Sport ist nur für junge Menschen gesund." }, { id: "b", text: "Kleine, regelmäßige Dosen Bewegung lassen sich leicht in den Alltag einbauen und helfen enorm." }, { id: "c", text: "Jeder Mensch sollte Leistungssportler werden." }], correctAnswer: "b" }
        ]
      },
      {
        part: "Teil 3",
        title: "Hörverstehen (Selektives Verstehen)",
        description: "Sie hören fünf kurze Ansagen (z.B. im Radio oder an Bahnhöfen). Entscheiden Sie bei den Aufgaben 56-60, ob die Aussage Richtig oder Falsch ist. Sie hören die Ansagen nur einmal.",
        items: [
          { id: 56, speaker: "Ansage 1", audioScript: "Aufgrund von Wartungsarbeiten an der Oberleitung ist der Streckenabschnitt zwischen Frankfurt Süd und Hanau Hauptbahnhof am kommenden Wochenende für den Zugverkehr gesperrt. Für Fahrgäste wird ein Schienenersatzverkehr mit Bussen eingerichtet. Die Busse fahren im 20-Minuten-Takt vor dem Hauptbahnhof ab. Bitte planen Sie eine längere Reisezeit ein.", statement: "Zwischen Frankfurt Süd und Hanau fahren am Wochenende Busse statt Züge.", correctAnswer: "Richtig" },
          { id: 57, speaker: "Ansage 2", audioScript: "Liebe Besucher des Einkaufszentrums. Wegen einer technischen Störung im Parkhaus West ist die Ausfahrt über die Schrankenanlagen derzeit nur im Erdgeschoss möglich. Parktickets können heute kostenfrei an den Kassenautomaten im Foyer entwertet werden. Wir bitten um Ihre Geduld.", statement: "Die Kunden können heute gratis im Einkaufszentrum parken.", correctAnswer: "Richtig" },
          { id: 58, speaker: "Ansage 3", audioScript: "Und hier eine Meldung für die Hörer unseres Klassiksenders. Das für heute Abend geplante Konzert der Philharmonie im großen Saal muss leider kurzfristig entfallen, da der Dirigent erkrankt ist. Ein Ersatztermin wird in den nächsten Tagen bekannt gegeben. Bereits gekaufte Karten können an den Vorverkaufsstellen zurückgegeben werden.", statement: "Das Klassikkonzert wird heute Abend von einem anderen Dirigenten geleitet.", correctAnswer: "Falsch" },
          { id: 59, speaker: "Ansage 4", audioScript: "Achtung an Gleis 3: Der Intercity-Express ICE 721 nach München über Nürnberg, Abfahrt um 11:45 Uhr, wird heute wegen einer Verspätung des Gegenlufes in umgekehrter Wagenreihung bereitgestellt. Die Waggons der 1. Klasse befinden sich heute im Abschnitt A, die Waggons der 2. Klasse im Abschnitt B und C.", statement: "Der ICE nach München kommt heute in einer anderen Reihenfolge als üblich an.", correctAnswer: "Richtig" },
          { id: 60, speaker: "Ansage 5", audioScript: "Sehr geehrte Fluggäste des Fluges DE 4920 nach Teneriffa. Das Boarding beginnt in wenigen Minuten an Gate C18. Wir bitten alle Passagiere, ihre Bordkarte und einen gültigen Lichtbildausweis zur Kontrolle bereitzuhalten. Fluggäste mit kleinen Kindern und Passagiere der Business Class dürfen zuerst an Bord gehen.", statement: "Beim Einstieg ins Flugzeug haben Familien mit Kindern Priorität.", correctAnswer: "Richtig" }
        ]
      }
    ]
  },

  // ==================== TEST SET 6 ====================
  {
    setId: 6,
    parts: [
      {
        part: "Teil 1",
        title: "Hörverstehen (Globalverstehen)",
        description: "Sie hören fünf kurze Aussagen von verschiedenen Personen zu einem Thema. Entscheiden Sie bei den Aufgaben 41-45, ob die jeweilige Aussage Richtig oder Falsch ist. Sie hören die Aussagen nur einmal.",
        topic: "Thema: Vegetarische Ernährung in Betrieben",
        items: [
          { id: 41, speaker: "Sprecher 1", audioScript: "In unserer Kantine gibt es jetzt einen verpflichtenden Veggie-Day pro Woche. Ich finde das unmöglich! Man sollte den Leuten doch nicht vorschreiben, was sie essen dürfen. Wenn ich donnerstags mein Schnitzel essen will, sollte ich das auch tun dürfen.", statement: "Sprecher 1 lehnt vorgeschriebene fleischfreie Tage in der Kantine ab.", correctAnswer: "Richtig" },
          { id: 42, speaker: "Sprecher 2", audioScript: "Ich finde die Neuerung klasse. Viele essen ohnehin viel zu viel Fleisch, was weder gesund ist noch gut fürs Klima. Ein vegetarischer Tag pro Woche in der Betriebskantine regt die Leute dazu an, mal neue Gerichte auszuprobieren. Das Essen schmeckt super.", statement: "Sprecher 2 befürwortet den vegetarischen Tag aus ökologischen und gesundheitlichen Gründen.", correctAnswer: "Richtig" },
          { id: 43, speaker: "Sprecher 3", audioScript: "Ich esse zwar Fleisch, aber mir ist es ehrlich gesagt völlig egal. Die Kantine bietet jeden Tag so viele verschiedene Gerichte an, dass immer etwas Leckeres dabei ist, egal ob mit oder ohne Fleisch. Man muss daraus doch kein Politikum machen.", statement: "Sprecher 3 ist die Debatte um das Essensangebot in der Kantine gleichgültig.", correctAnswer: "Richtig" },
          { id: 44, speaker: "Sprecher 4", audioScript: "Unser Arbeitgeber hat die Fleischgerichte in der Kantine komplett gestrichen. Seitdem gehen viele Kollegen in den Pausen lieber zum Dönerladen oder Bäcker um die Ecke. Die Kantine macht jetzt viel weniger Umsatz, das Konzept ist also nach hinten losgegangen.", statement: "Sprecher 4 berichtet von sinkenden Kundenzahlen in der Kantine nach der Umstellung.", correctAnswer: "Richtig" },
          { id: 45, speaker: "Sprecher 5", audioScript: "Es geht doch vor allem um die Qualität. Wenn das Fleisch billig produziert wird, schmeckt es ohnehin nicht. Ich wäre bereit, mehr Geld für Fleisch aus artgerechter Haltung zu bezahlen. Ein generelles Verbot in der Kantine halte ich aber für den falschen Weg.", statement: "Sprecher 5 wünscht sich qualitativ hochwertiges Fleisch aus guter Tierhaltung statt eines Verbots.", correctAnswer: "Richtig" }
        ]
      },
      {
        part: "Teil 2",
        title: "Hörverstehen (Detailverstehen)",
        description: "Sie hören ein Gespräch oder Interview. Wählen Sie bei den Aufgaben 46-55 die richtige Antwort (a, b oder c). Sie hören den Text nur einmal.",
        topic: "Interview: Digitalisierung an Schulen",
        audioScript: "Moderator: Herzlich willkommen zu unserem wöchentlichen Magazin 'Bildung im Fokus'. Wir sprechen heute mit der Schulleiterin Frau Dr. Sabine Fischer über das Thema Digitalisierung an Schulen. Frau Dr. Fischer, wie steht es um den Einsatz digitaler Medien an Ihrer Schule?\n\nDr. Fischer: Guten Tag. Wir haben in den letzten drei Jahren große Fortschritte gemacht. Dank staatlicher Fördermittel konnten wir alle Klassenzimmer mit interaktiven Smartboards ausstatten und Schülern der höheren Klassen Leih-Tablets zur Verfügung stellen. Die klassische Tafel aus Kreide gibt es bei uns kaum noch.\n\nModerator: Viele Kritiker warnen jedoch, dass die ständige Bildschirmnutzung die Konzentrationsfähigkeit der Kinder verringert. Wie sehen Sie das?\n\nDr. Fischer: Diese Sorge ist nicht ganz unberechtigt. Es kommt auf das richtige Maß an. Tablets dürfen kein Ersatz für das eigene Denken und Schreiben sein. Wir nutzen sie gezielt für Recherchen, das Lösen von interaktiven Geometrie-Aufgaben oder zum Lernen von Vokabeln über Apps. Das klassische Schulbuch aus Papier hat bei uns nach wie vor seinen festen Platz.\n\nModerator: Ein weiteres Problem ist oft, dass die Lehrkräfte technisch nicht ausreichend geschult sind. Wie haben Sie das gelöst?\n\nDr. Fischer: Das war anfangs in der Tat eine Hürde. Wir haben daher ein internes Fortbildungsprogramm gestartet. Jüngere Kollegen, die technisch sehr versiert sind, unterstützen ältere Dozenten im Alltag. Das funktioniert im Team hervorragend.\n\nModerator: Frau Dr. Fischer, vielen Dank für das Gespräch.",
        questions: [
          { id: 46, question: "Welche Position hat Sabine Fischer inne?", options: [{ id: "a", text: "Eine Gymnasiallehrerin." }, { id: "b", text: "Die Schulleiterin." }, { id: "c", text: "Eine Vertreterin des Kultusministeriums." }], correctAnswer: "b" },
          { id: 47, question: "Welche Anschaffungen wurden an der Schule in den letzten drei Jahren getätigt?", options: [{ id: "a", text: "Smartboards in den Klassen und Leih-Tablets für ältere Schüler." }, { id: "b", text: "Smartphones für alle Schüler gratis." }, { id: "c", text: "Neue Holztafeln und Kreideboxen." }], correctAnswer: "a" },
          { id: 48, question: "Wie steht Dr. Fischer zum Risiko der Bildschirmnutzung?", options: [{ id: "a", text: "Sie hält die Bedenken für absolut unbegründet." }, { id: "b", text: "Sie sieht Gefahren bei zu viel Nutzung und plädiert für einen ausgewogenen Einsatz." }, { id: "c", text: "Sie fordert ein Verbot von Papier-Schulbüchern." }], correctAnswer: "b" },
          { id: 49, question: "Für welche schulischen Aktivitäten werden die Tablets vor allem genutzt?", options: [{ id: "a", text: "Um in Prüfungen im Internet nach Antworten zu suchen." }, { id: "b", text: "Für Vokabel-Apps, Recherchen und Geometrie-Aufgaben." }, { id: "c", text: "Ausschließlich zum Spielen in den Pausen." }], correctAnswer: "b" },
          { id: 50, question: "Wie steht es um das klassische Schulbuch an Fischers Schule?", options: [{ id: "a", text: "Es wurde komplett abgeschafft." }, { id: "b", text: "Es wird weiterhin regulär im Unterricht genutzt." }, { id: "c", text: "Es darf nur noch digital gelesen werden." }], correctAnswer: "b" },
          { id: 51, question: "Welches Problem gab es anfangs mit dem Lehrpersonal?", options: [{ id: "a", text: "Viele Lehrer weigerten sich, den Smartboard-Unterricht zu halten." }, { id: "b", text: "Es gab Wissenslücken bei der technischen Bedienung der Geräte." }, { id: "c", text: "Die Lehrer forderten höhere Gehälter für Digitalunterricht." }], correctAnswer: "b" },
          { id: 52, question: "Wie wurde das Fortbildungsproblem gelöst?", options: [{ id: "a", text: "Durch teure externe Berater." }, { id: "b", text: "Durch ein internes System, bei dem jüngere Lehrer älteren Kollegen helfen." }, { id: "c", text: "Die Lehrer mussten Kurse an der Volkshochschule belegen." }], correctAnswer: "b" },
          { id: 53, question: "Welche Fördermittel ermöglichten den Umbau der Schule?", options: [{ id: "a", text: "Private Spenden von Eltern." }, { id: "b", text: "Staatliche Fördermittel." }, { id: "c", text: "Kredite von Banken." }], correctAnswer: "b" },
          { id: 54, question: "Welches traditionelle Unterrichtswerkzeug gibt es laut Dr. Fischer kaum noch?", options: [{ id: "a", text: "Den Kugelschreiber." }, { id: "b", text: "Die klassische Kreidetafel." }, { id: "c", text: "Das Notizheft aus Papier." }], correctAnswer: "b" },
          { id: 55, question: "Wie schätzt Fischer den Erfolg der Digitalisierung insgesamt ein?", options: [{ id: "a", text: "Als gescheitertes Experiment." }, { id: "b", text: "Als großen und lohnenden Fortschritt für das gemeinsame Lernen." }, { id: "c", text: "Als billige Methode, um Lehrerstellen einzusparen." }], correctAnswer: "b" }
        ]
      },
      {
        part: "Teil 3",
        title: "Hörverstehen (Selektives Verstehen)",
        description: "Sie hören fünf kurze Ansagen (z.B. im Radio oder an Bahnhöfen). Entscheiden Sie bei den Aufgaben 56-60, ob die Aussage Richtig oder Falsch ist. Sie hören die Ansagen nur einmal.",
        items: [
          { id: 56, speaker: "Ansage 1", audioScript: "Achtung an alle Badegäste des Freibads. Wegen eines aufziehenden schweren Gewitters über dem Stadtgebiet müssen alle Schwimmbecken aus Sicherheitsgründen mit sofortiger Wirkung geräumt werden. Wir bitten Sie, das Wasser unverzüglich zu verlassen und Schutz in den Umkleidegebäuden zu suchen. Die Liegewiesen sind ebenfalls zu räumen.", statement: "Die Badegäste müssen das Schwimmbecken wegen eines nahenden Gewitters verlassen.", correctAnswer: "Richtig" },
          { id: 57, speaker: "Ansage 2", audioScript: "Fahrgäste des ICE 591 nach Dresden Hauptbahnhof. Wegen einer Streckensperrung nach einem Baumsturz auf die Gleise wird dieser Zug heute über Leipzig umgeleitet. Die Zwischenhalte in Erfurt und Weimar entfallen. Der Zug verspätet sich um voraussichtlich 400 Minuten. Wir bitten um Ihr Verständnis.", statement: "Der Zug nach Dresden hält heute nicht an allen planmäßigen Stationen.", correctAnswer: "Richtig" },
          { id: 58, speaker: "Ansage 3", audioScript: "Wir unterbrechen das Programm für eine Gefahrenmeldung der Polizei. Auf der B45 zwischen Dieburg und Groß-Umstadt läuft eine Herde entlaufener Kühe auf der Fahrbahn. Bitte fahren Sie in beiden Richtungen vorsichtig, überholen Sie nicht und achten Sie auf die Fahrbahnränder.", statement: "Autofahrer auf der B45 sollen auf Tiere auf der Straße achten.", correctAnswer: "Richtig" },
          { id: 59, speaker: "Ansage 4", audioScript: "Liebe Kundinnen und Kunden. Besuchen Sie unsere Sportabteilung im 2. Obergeschoss. Nur in dieser Woche erhalten Sie beim Kauf von Laufschuhen eine professionelle Laufbandanalyse gratis dazu. Zudem gewähren wir 10 Prozent Rabatt auf alle Sportbekleidungsartikel der neuen Saison.", statement: "Das Angebot der kostenfreien Laufbandanalyse gilt exklusiv am Wochenende.", correctAnswer: "Falsch" },
          { id: 60, speaker: "Ansage 5", audioScript: "Sehr geehrte Fluggäste des LH-Fluges nach München, planmäßige Abfahrt um 16 Uhr. Aufgrund eines verspäteten Eintreffens des Flugzeugs verschiebt sich das Boarding um eine halbe Stunde auf 16:15 Uhr. Das neue Abfluggate ist B24 statt wie zuvor angekündigt A12.", statement: "Das Abfluggate für den Flug nach München hat sich geändert.", correctAnswer: "Richtig" }
        ]
      }
    ]
  },

  // ==================== TEST SET 7 ====================
  {
    setId: 7,
    parts: [
      {
        part: "Teil 1",
        title: "Hörverstehen (Globalverstehen)",
        description: "Sie hören fünf kurze Aussagen von verschiedenen Personen zu einem Thema. Entscheiden Sie bei den Aufgaben 41-45, ob die jeweilige Aussage Richtig oder Falsch ist. Sie hören die Aussagen nur einmal.",
        topic: "Thema: Nutzung von E-Books vs. gedruckten Büchern",
        items: [
          { id: 41, speaker: "Sprecher 1", audioScript: "Für mich geht nichts über den Geruch und das Gefühl eines echten, gedruckten Buches. Ein E-Book-Reader fühlt sich einfach kalt und unpersönlich an. Außerdem möchte ich meine gelesenen Bücher stolz im Regal präsentieren.", statement: "Sprecher 1 zieht gedruckte Bücher aus emotionalen und ästhetischen Gründen vor.", correctAnswer: "Richtig" },
          { id: 42, speaker: "Sprecher 2", audioScript: "E-Reader sind auf Reisen unschlagbar. Früher musste ich immer drei dicke Wälzer im Koffer mitschleppen, was viel Gewicht gekostet hat. Jetzt habe ich Hunderte von Büchern auf einem kleinen, leichten Gerät dabei. Das ist extrem komfortabel.", statement: "Sprecher 2 schätzt das geringe Gewicht und die Kapazität von E-Readern auf Reisen.", correctAnswer: "Richtig" },
          { id: 43, speaker: "Sprecher 3", audioScript: "Ich finde E-Books toll, weil man die Schriftgröße individuell anpassen kann. Da ich nicht mehr ganz so gut sehe, ist das für mich eine enorme Erleichterung. Auch die integrierte Wörterbuchfunktion nutze ich sehr oft für fremdsprachige Romane.", statement: "Sprecher 3 nutzt E-Reader vor allem wegen praktischer Funktionen wie Schriftgrößenanpassung.", correctAnswer: "Richtig" },
          { id: 44, speaker: "Sprecher 4", audioScript: "Es ist ein großer Vorteil, dass man E-Books sofort herunterladen und lesen kann, ohne das Haus zu verlassen oder auf die Post zu warten. Zudem sind sie oft etwas günstiger als die gedruckten Ausgaben. Das spart Zeit und Geld.", statement: "Sprecher 4 hebt die schnelle Verfügbarkeit und den Preisvorteil von E-Books hervor.", correctAnswer: "Richtig" },
          { id: 45, speaker: "Sprecher 5", audioScript: "Ich mache mir Sorgen um den Datenschutz bei diesen Geräten. Die Anbieter wissen genau, wann ich welches Buch lese, wie schnell ich umblättere und welche Passagen ich markiere. Diese totale Überwachung gefällt mir überhaupt nicht.", statement: "Sprecher 5 lehnt E-Reader ab, weil er sich um die Aufzeichnung seines Leseverhaltens sorgt.", correctAnswer: "Richtig" }
        ]
      },
      {
        part: "Teil 2",
        title: "Hörverstehen (Detailverstehen)",
        description: "Sie hören ein Gespräch oder Interview. Wählen Sie bei den Aufgaben 46-55 die richtige Antwort (a, b oder c). Sie hören den Text nur einmal.",
        topic: "Interview: Carsharing in Großstädten",
        audioScript: "Moderator: Willkommen bei 'Urbane Mobilität'. Heute sprechen wir mit Frau Julia Krüger vom Verband für Carsharing. Frau Krüger, Carsharing boomt in deutschen Städten. Wer nutzt dieses Angebot hauptsächlich?\n\nFrau Krüger: Guten Tag. Die Hauptnutzer sind jüngere Erwachsene zwischen 25 und 40 Jahren, die in Ballungsräumen leben. Viele von ihnen haben sich bewusst gegen ein eigenes Auto entschieden, da die Fixkosten für Versicherung, Steuer und Stellplätze in Großstädten einfach zu hoch sind.\n\nModerator: Welche Vorteile bietet Carsharing im Vergleich zum eigenen Pkw?\n\nFrau Krüger: Neben der Kostenersparnis ist es vor allem die Flexibilität. Man bucht das Auto per App nur für den Zeitraum, in dem man es tatsächlich benötigt. Zudem entfallen lästige Aufgaben wie Wartung, Reifenwechsel oder TÜV-Besuche. Das übernimmt alles der Anbieter.\n\nModerator: Kritiker bemängeln allerdings, dass Carsharing-Autos oft nicht sauber sind oder im entscheidenden Moment kein Fahrzeug in der Nähe verfügbar ist. Was sagen Sie dazu?\n\nFrau Krüger: Das Sauberkeitsproblem existiert leider manchmal, da wir auf die Rücksichtnahme der Kunden angewiesen sind. Zur Verfügbarkeit: Wir erweitern unsere Flotten stetig, aber in Stoßzeiten wie am Freitagnachmittag kann es tatsächlich eng werden. Hier empfiehlt sich eine frühzeitige Reservierung.\n\nModerator: Frau Krüger, vielen Dank für das informative Gespräch.",
        questions: [
          { id: 46, question: "Welche Position hat Frau Julia Krüger?", options: [{ id: "a", text: "Sie arbeitet bei einer Autovermietung." }, { id: "b", text: "Sie ist Vertreterin des Carsharing-Verbands." }, { id: "c", text: "Sie ist Verkehrsplanerin der Stadt." }], correctAnswer: "b" },
          { id: 47, question: "Wer ist die typische Zielgruppe für Carsharing laut Krüger?", options: [{ id: "a", text: "Senioren auf dem Land." }, { id: "b", text: "Jüngere Erwachsene in Großstädten zwischen 25 und 40 Jahren." }, { id: "c", text: "Familien mit vielen Kindern." }], correctAnswer: "b" },
          { id: 48, question: "Welcher finanzielle Vorteil wird für die Nutzer genannt?", options: [{ id: "a", text: "Die Autos verbrauchen kein Benzin." }, { id: "b", text: "Man spart sich die hohen Fixkosten für einen eigenen Pkw." }, { id: "c", text: "Die Nutzung ist für Studenten komplett kostenfrei." }], correctAnswer: "b" },
          { id: 49, question: "Welche Aufgaben übernimmt der Carsharing-Anbieter für den Kunden?", options: [{ id: "a", text: "Die Routenplanung während der Fahrt." }, { id: "b", text: "Wartung, TÜV-Prüfungen und Reifenwechsel." }, { id: "c", text: "Die Reinigung nach absolut jeder Fahrt." }], correctAnswer: "b" },
          { id: 50, question: "Warum klagen manche Kunden über die Sauberkeit der Fahrzeuge?", options: [{ id: "a", text: "Weil die Anbieter die Autos absichtlich verschmutzen." }, { id: "b", text: "Weil manche Nutzer die Fahrzeuge nicht ordentlich hinterlassen." }, { id: "c", text: "Weil die Autos sehr alt sind." }], correctAnswer: "b" },
          { id: 51, question: "Wann kann es laut Krüger zu Engpässen bei der Verfügbarkeit kommen?", options: [{ id: "a", text: "Ausschließlich an Feiertagen im Winter." }, { id: "b", text: "In Stoßzeiten wie zum Beispiel am Freitagnachmittag." }, { id: "c", text: "Überhaupt nie, es sind immer genug Autos da." }], correctAnswer: "b" },
          { id: 52, question: "Was empfiehlt Frau Krüger, um sicher ein Auto zu bekommen?", options: [{ id: "a", text: "Sich ein eigenes Auto zu kaufen." }, { id: "b", text: "Das gewünschte Fahrzeug frühzeitig zu reservieren." }, { id: "c", text: "Nur nachts zu fahren." }], correctAnswer: "b" },
          { id: 53, question: "Wie bucht man ein Carsharing-Auto in der Regel?", options: [{ id: "a", text: "Per Telefonanruf bei der Zentrale." }, { id: "b", text: "Ganz einfach über eine Smartphone-App." }, { id: "c", text: "Durch das Ausfüllen eines Formulars auf Papier." }], correctAnswer: "b" },
          { id: 54, question: "Warum verzichten Großstädter laut Text vermehrt auf eigene Autos?", options: [{ id: "a", text: "Weil Autofahren verboten wurde." }, { id: "b", text: "Wegen hoher Fixkosten und Parkplatzmangel." }, { id: "c", text: "Weil sie lieber zu Fuß gehen." }], correctAnswer: "b" },
          { id: 55, question: "Wie wird die Flexibilität von Carsharing begründet?", options: [{ id: "a", text: "Man kann überall kostenlos parken." }, { id: "b", text: "Man bucht und bezahlt das Auto nur für den tatsächlichen Nutzungszeitraum." }, { id: "c", text: "Die Autos können fliegen." }], correctAnswer: "b" }
        ]
      },
      {
        part: "Teil 3",
        title: "Hörverstehen (Selektives Verstehen)",
        description: "Sie hören fünf kurze Ansagen (z.B. im Radio oder an Bahnhöfen). Entscheiden Sie bei den Aufgaben 56-60, ob die Aussage Richtig oder Falsch ist. Sie hören die Ansagen nur einmal.",
        items: [
          { id: 56, speaker: "Ansage 1", audioScript: "Achtung an alle Besucher der Verbrauchermesse. Am Stand der Firma Elektro-Zukunft in Halle 4 zeigen wir stündlich Vorführungen der neuesten Roboter-Staubsauger. Zudem erhalten Sie bei Abschluss eines Abonnements unserer Heimwerker-Zeitschrift ein hochwertiges Werkzeugset geschenkt. Besuchen Sie uns!", statement: "Am Stand von Elektro-Zukunft gibt es jede Stunde eine Produktpräsentation.", correctAnswer: "Richtig" },
          { id: 57, speaker: "Ansage 2", audioScript: "Wegen einer Stellwerkstörung im Raum Mannheim kommt es aktuell zu Verspätungen und Teilausfällen im Regionalverkehr. Der Regional-Express RE 4 nach Mainz fällt heute ersatzlos aus. Fahrgäste nutzen bitte alternativ die S-Bahn-Linie S6 nach Mainz, die an allen Stationen hält.", statement: "Der RE 4 nach Mainz fährt heute mit einer Verspätung von 30 Minuten ab.", correctAnswer: "Falsch" },
          { id: 58, speaker: "Ansage 3", audioScript: "Sehr geehrte Fluggäste des Fluges LH 2048 nach Paris. Bitte beachten Sie die geänderte Sicherheitsregelung für das Handgepäck. Flüssigkeiten dürfen ab sofort nur noch in Behältern mit maximal 100 Millilitern mitgeführt werden, die in einem durchsichtigen, wiederverschließbaren Plastikbeutel verpackt sein müssen.", statement: "Flüssigkeiten im Handgepäck müssen in einen transparenten Beutel gepackt werden.", correctAnswer: "Richtig" },
          { id: 59, speaker: "Ansage 4", audioScript: "Hier ist der Wetterbericht für morgen. Nach Auflösung lokaler Nebelfelder erwartet uns ein strahlend sonniger und warmer Spätherbsttag mit Temperaturen bis zu 22 Grad im Rheintal. Erst am späten Abend ziehen von Westen her dichte Wolkenfelder auf, die in der Nacht Regen bringen.", statement: "Morgen wird es tagsüber überwiegend sonnig und mild.", correctAnswer: "Richtig" },
          { id: 60, speaker: "Ansage 5", audioScript: "Liebe Kunden unserer Buchhandlung. Wir laden Sie herzlich zu unserer Autorenlesung am Donnerstagabend um 20 Uhr ein. Der Bestsellerautor Sebastian Fitzek liest aus seinem neuesten Psychothriller. Der Eintritt ist frei, eine Reservierung über unsere Homepage ist jedoch zwingend erforderlich.", statement: "Für die Autorenlesung muss man Eintrittskarten kaufen.", correctAnswer: "Falsch" }
        ]
      }
    ]
  },

  // ==================== TEST SET 8 ====================
  {
    setId: 8,
    parts: [
      {
        part: "Teil 1",
        title: "Hörverstehen (Globalverstehen)",
        description: "Sie hören fünf kurze Aussagen von verschiedenen Personen zu einem Thema. Entscheiden Sie bei den Aufgaben 41-45, ob die Aussage Richtig oder Falsch ist. Sie hören die Aussagen nur einmal.",
        topic: "Thema: Homeschooling und Distanzunterricht",
        items: [
          { id: 41, speaker: "Sprecher 1", audioScript: "Für meine Kinder war der Distanzunterricht eine Katastrophe. Ihnen fehlte der direkte Kontakt zu den Mitschülern und Lehrern enorm. Zudem war es technisch oft sehr schwierig, da unsere Internetverbindung ständig abbrach und wir nicht genug Laptops hatten.", statement: "Sprecher 1 berichtet von technischen und sozialen Problemen beim Homeschooling.", correctAnswer: "Richtig" },
          { id: 42, speaker: "Sprecher 2", audioScript: "Ich fand das Homeschooling eigentlich ganz entspannend. Man konnte länger schlafen, da der Schulweg wegfiel, und sich die Lernzeit flexibler einteilen. Für mich hat das selbstständige Arbeiten mit den digitalen Aufgabenplattformen super funktioniert.", statement: "Sprecher 2 empfand den Distanzunterricht als flexibel und stressfreier.", correctAnswer: "Richtig" },
          { id: 43, speaker: "Sprecher 3", audioScript: "Die Lehrer waren völlig überfordert! Manche haben nur Aufgabenlisten per Mail geschickt, ohne sie jemals zu besprechen. Andererseits gab es Lehrer, die stundenlange Videokonferenzen abgehalten haben, bei denen die Kinder kaum etwas verstanden haben. Es gab kein einheitliches Konzept.", statement: "Sprecher 3 kritisiert das unkoordinierte Vorgehen der Lehrkräfte beim Homeschooling.", correctAnswer: "Richtig" },
          { id: 44, speaker: "Sprecher 4", audioScript: "Als berufstätige Mutter war das eine enorme Belastung. Man musste gleichzeitig im Homeoffice arbeiten und die Kinder beim Lernen betreuen, da sie sich allein nicht konzentrieren konnten. Ich bin an meine Grenzen gestoßen und hoffe, dass die Schulen immer offen bleiben.", statement: "Sprecher 4 sah im Homeschooling eine extreme Doppelbelastung für berufstätige Eltern.", correctAnswer: "Richtig" },
          { id: 45, speaker: "Sprecher 5", audioScript: "Man hat deutlich gesehen, wie sozial ungerecht dieses System ist. Kinder aus einkommensschwachen Familien, die kein eigenes Zimmer oder keinen PC haben, wurden komplett abgehängt. Die Politik hätte viel schneller für kostenlose Leihgeräte sorgen müssen.", statement: "Sprecher5 meint, dass alle Kinder die gleichen technischen Voraussetzungen zu Hause hatten.", correctAnswer: "Falsch" }
        ]
      },
      {
        part: "Teil 2",
        title: "Hörverstehen (Detailverstehen)",
        description: "Sie hören ein Gespräch oder Interview. Wählen Sie bei den Aufgaben 46-55 die richtige Antwort (a, b oder c). Sie hören den Text nur einmal.",
        topic: "Interview: Nachhaltiger Tourismus",
        audioScript: "Moderator: Herzlich willkommen zu 'Reisen und Zukunft'. Heute im Studio sprechen wir mit Herrn Christian Becker vom Verein für sanften Tourismus. Herr Becker, was versteht man eigentlich unter nachhaltigem Reisen?\n\nDr. Becker: Guten Tag. Nachhaltiger Tourismus bedeutet, so zu reisen, dass die Natur geschont und die lokale Bevölkerung wirtschaftlich unterstützt wird. Es geht darum, den ökologischen Fußabdruck zu minimieren und die Kultur des Reiselandes zu respektieren.\n\nModerator: Viele Menschen fliegen mehrmals im Jahr in den Urlaub. Ist Fliegen mit nachhaltigem Tourismus überhaupt vereinbar?\n\nDr. Becker: Das ist in der Tat das größte Problem. Flugreisen verursachen enorme CO2-Emissionen. Wer nachhaltig reisen möchte, sollte auf Kurzstreckenflüge verzichten und stattdessen die Bahn nutzen. Für Fernreisen gilt die Regel: seltener fliegen, dafür aber länger am Urlaubsort bleiben, anstatt für eine Woche nach Übersee zu reisen.\n\nModerator: Welche Kriterien sollten Urlauber bei der Wahl ihrer Unterkunft beachten?\n\nDr. Becker: Man sollte Unterkünfte wählen, die umweltfreundlich geführt werden – zum Beispiel durch die Nutzung von Solarenergie, regionale Bio-Lebensmittel beim Frühstück und den Verzicht auf Plastikverpackungen. Zudem sollte das Hotel faire Löhne an die einheimischen Mitarbeiter zahlen.\n\nModerator: Herr Dr. Becker, vielen Dank für diese Ratschläge.",
        questions: [
          { id: 46, question: "Wer ist Herr Christian Becker?", options: [{ id: "a", text: "Ein Hotelbesitzer." }, { id: "b", text: "Ein Vertreter des Vereins für sanften Tourismus." }, { id: "c", text: "Ein Reiseleiter." }], correctAnswer: "b" },
          { id: 47, question: "Was ist ein Hauptziel des nachhaltigen Tourismus?", options: [{ id: "a", text: "Möglichst billige Urlaubsreisen anzubieten." }, { id: "b", text: "Die Natur zu schonen und die lokale Bevölkerung zu unterstützen." }, { id: "c", text: "Neue Luxushotels zu bauen." }], correctAnswer: "b" },
          { id: 48, question: "Welches Transportmittel empfiehlt Becker für Kurzstrecken?", options: [{ id: "a", text: "Das Flugzeug." }, { id: "b", text: "Die Bahn." }, { id: "c", text: "Den Fernbus." }], correctAnswer: "b" },
          { id: 49, question: "Welchen Ratschlag gibt Becker für unvermeidbare Fernreisen?", options: [{ id: "a", text: "Gar keine Fernreisen mehr zu unternehmen." }, { id: "b", text: "Seltener zu fliegen, aber dafür länger am Urlaubsort zu bleiben." }, { id: "c", text: "Nur Billigflieger zu nutzen." }], correctAnswer: "b" },
          { id: 50, question: "Was kennzeichnet eine nachhaltige Unterkunft beim Frühstück?", options: [{ id: "a", text: "Ein Buffet mit Importwaren." }, { id: "b", text: "Regionale Bio-Lebensmittel und Plastikverzicht." }, { id: "c", text: "Ausschließlich warme Speisen." }], correctAnswer: "b" },
          { id: 51, question: "Welche soziale Komponente nennt Becker für Hotels?", options: [{ id: "a", text: "Die Vermietung von Fahrrädern." }, { id: "b", text: "Die Zahlung fairer Löhne an einheimische Angestellte." }, { id: "c", text: "Kostenlose Spa-Nutzung." }], correctAnswer: "b" },
          { id: 52, question: "Warum sind Flugreisen laut Interview problematisch?", options: [{ id: "a", text: "Weil tickets zu teuer sind." }, { id: "b", text: "Wegen der hohen CO2-Emissionen." }, { id: "c", text: "Weil Flüge oft unpünktlich sind." }], correctAnswer: "b" },
          { id: 53, question: "Was meint Becker mit dem respektvollen Umgang mit der Kultur?", options: [{ id: "a", text: "Die Landessprache fließend zu lernen." }, { id: "b", text: "Die Sitten und Bräuche vor Ort zu respektieren." }, { id: "c", text: "Nur in Kulturmuseen zu gehen." }], correctAnswer: "b" },
          { id: 54, question: "Welche Energiequelle sollten nachhaltige Hotels nutzen?", options: [{ id: "a", text: "Atomkraft." }, { id: "b", text: "Solarenergie oder andere erneuerbare Energien." }, { id: "c", text: "Kohlekraftwerke." }], correctAnswer: "b" },
          { id: 55, question: "Was ist die Kernaussage von Becker zur Urlaubsplanung?", options: [{ id: "a", text: "Es ist unmöglich, umweltfreundlich zu reisen." }, { id: "b", text: "Durch bewusste Entscheidungen bei Transport und Unterkunft lässt sich der Urlaub umweltschonend gestalten." }, { id: "c", text: "Man sollte nur noch zu Hause Urlaub machen." }], correctAnswer: "b" }
        ]
      },
      {
        part: "Teil 3",
        title: "Hörverstehen (Selektives Verstehen)",
        description: "Sie hören fünf kurze Ansagen (z.B. im Radio oder an Bahnhöfen). Entscheiden Sie bei den Aufgaben 56-60, ob die Aussage Richtig oder Falsch ist. Sie hören die Ansagen nur einmal.",
        items: [
          { id: 56, speaker: "Ansage 1", audioScript: "Wegen dringend erforderlicher Reinigungsarbeiten nach einem Wasserrohrbruch bleibt das städtische Hallenbad am kommenden Donnerstag für den gesamten Publikumsverkehr geschlossen. Alle Schwimmkurse am Nachmittag fallen aus und werden zu einem späteren Zeitpunkt nachgeholt. Ab Freitag hat das Bad wieder regulär geöffnet.", statement: "Das Hallenbad bleibt wegen eines Wasserschadens am Donnerstag zu.", correctAnswer: "Richtig" },
          { id: 57, speaker: "Ansage 2", audioScript: "Sehr geehrte Fahrgäste der Stadtbahnlinie U2. Wegen einer Gleissperrung nach einem Verkehrsunfall im Kreuzungsbereich fährt die U2 derzeit nur zwischen Hauptbahnhof und Südfriedhof. Für den gesperrten Streckenabschnitt bis zur Endstation Nordweststadt ist ein Ersatzverkehr mit Taxis eingerichtet.", statement: "Für die blockierten Haltestellen der U2 gibt es Ersatztaxis.", correctAnswer: "Richtig" },
          { id: 58, speaker: "Ansage 3", audioScript: "Achtung im Autobahndreieck Köln-Ost. Nach einem Erdrutsch ist die Überfahrt zur A4 Richtung Olpe wegen Aufräumarbeiten gesperrt. Eine Umleitung über die B55 ist ausgeschildert. Bitte folgen Sie den roten Punkten. Mit erheblichem Zeitverlust ist zu rechnen.", statement: "Autofahrer können die A4 Richtung Olpe über die normale Abfahrt ungehindert erreichen.", correctAnswer: "Falsch" },
          { id: 59, speaker: "Ansage 4", audioScript: "Liebe Kundinnen und Kunden. In unserer Drogerieabteilung im Erdgeschoss erhalten Sie nur heute beim Kauf eines Parfüms eine feuchtigkeitsspendende Handcreme gratis dazu. Zudem gewähren wir 15 Prozent Rabatt auf alle Kosmetikartikel bekannter Marken. Greifen Sie zu!", statement: "Das Sonderangebot der Drogerie gilt ausschließlich am heutigen Tag.", correctAnswer: "Richtig" },
          { id: 60, speaker: "Ansage 5", audioScript: "Sehr geehrte Fahrgäste an Gleis 5. Bitte beachten Sie: Der Regional-Express RE 9 nach Siegen, Planabfahrt um 14:30 Uhr, wird heute wegen einer verspäteten Bereitstellung nicht von Gleis 5, sondern von Gleis 12 abfahren. Wir bitten um Entschuldigung.", statement: "Der RE 9 fährt heute von einem anderen Bahnsteig ab.", correctAnswer: "Richtig" }
        ]
      }
    ]
  }
];

